---
title: "Conclusions"
author: "Kyle Killion"
date: "June 2, 2016"
  html_document:
    keep_md: true
---

attach(bk)

```{r}
attach(bk)
```

### Family Distributions BreakDown
```{r}
knitr::opts_chunk$set(cache=TRUE)

bk.homes <- bk.homes[which(bk.homes$outliers==0),]
bk.homes$outliers <- (log10(bk.homes$sale.price.n) <=5) + 0


thing <- c('ONE FAMILY','TWO FAMILY','THREE FAMILY')

for (i in thing){
  Fam <- bk.homes[which(grepl(i, bk.homes$building.class.category)),]
  print(i)
  print(paste('Avg Gross sqft : ', mean(Fam$gross.sqft)))
  print(paste("SD : ", sd(Fam$gross.sqft)))
  print(paste('Avg Sale Price : ', mean(Fam$sale.price.n)))
  print(paste("SD :", sd(Fam$sale.price.n)))
  plot(log(Fam$gross.sqft),log(Fam$sale.price.n),
     xlab = 'Gross sqft',
     ylab = 'Sales Price $',
     main = i)
  
  #Sqrt the Sales Prices instead of Log
  hist(sqrt(Fam$sale.price.n),
       main = i,
       xlab = 'Sales Price $')
  
  boxplot(log(Fam$sale.price.n), xlab = i,
          ylab = 'Sales Price')
  
  boxplot(log(Fam$gross.sqft), xlab = i,
          ylab = 'Gross sqft')
}

```

### Conclusion

###The sales price average for the Family of 3 carried the highest value at $641,171. The Family of two carried the lowest average sales price of $606,132. The Family of 1 carried the highest spread of data within sales price indicating that they have more income at disposal. 
